name = "Immersive Horizons"
author = "Pelayo-Chacon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae4536b008942134db8dcc2bee4676e1b948987ee6f45a6e447938eafc287f96"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
