name = "Immersive Horizons"
author = "Pelayo-Chacon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3f4ab4dbab047d7ab982c8090c64c2a17e816859ade0c85bef8f928094c1adf"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
